### ISSUE TITLE
the attached file causes 'out of buffer' error

### ISSUE THREAD

**Issue by dvirtz** [dvirtz/vscode-parquet-viewer#1]
[part-00000-5c2c4a6f-a7f9-4f0e-a19f-47bbeac1242a.c000.snappy.parquet.zip](https://github.com/dvirtz/vscode-parquet-viewer/files/2910674/part-00000-5c2c4a6f-a7f9-4f0e-a19f-47bbeac1242a.c000.snappy.parquet.zip)

**Comment by macdonst** [comment]
I'm getting the following error:

```
error when running parquet-tools RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded:
```

Is it the same as what you are seeing.

**Comment by dvirtz** [comment]
Does it work for you when you run parquet-tools manually?

**Comment by macdonst** [comment]
@dvirtz yeah, I can view the file from the CLI using parquet-tools.

**Comment by dvirtz** [comment]
@macdonst please try version 0.1.1

**Comment by macdonst** [comment]
@dvirtz I updated and it works great. Thanks for the fix.
