### ISSUE TITLE
Does not support LargeUtf8

### ISSUE THREAD

**Issue by evbo** [dvirtz/vscode-parquet-viewer#105]
Get error trying to view py-polars parquet file:
> {"error":"while reading /Users/bik_borfer/git/db.parquet: Error: Unrecognized type: \"LargeUtf8\" (20)"}

**Comment by dvirtz** [comment]
Thanks for opening an issue. Could you upload a sample parquet here? That will speed up the fix.

**Comment by evbo** [comment]
github won't let me upload parquet files, but here is how I create it using `polars`
```python
import polars as pl
df = pl.from_dicts([{"a": "hello"}])
df.write_parquet(parquet_out_path)
```

> polars==0.20.2
connectorx==0.3.2
pyarrow==14.0.2
boto3==1.26.130

**Comment by dvirtz** [comment]
This is due to https://github.com/apache/arrow/issues/15060 which is fixed in main but the fix is not released yet.

**Comment by evbo** [comment]
@dvirtz Great! Is it possible to enable "pre-release" for this extension so that from the VS Code IDE I am able to get latest main commits at my discretion?

**Comment by dvirtz** [comment]
Unfortunately, it's a bug in one of the dependencies so we'll have to wait for their release.
Maybe there's a way to make `polars` not use this type in the meantime?

**Comment by kylebarron** [comment]
Polars is not interested in supporting both offset sizes due to maintenance and compilation overhead

**Comment by dvirtz** [comment]
apache-arrow 15.0 was released. I'll check later today if that fixes issue.

**Comment by evbo** [comment]
@dvirtz strangely it now works on my M2 Mac but not in my ARM64 Linux VM...

Mac VS Code version:
> Version: 1.86.2 (Universal)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:42:13.651Z (1 wk ago)
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 22.3.0

Linux:
> Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:59.576Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux arm64 5.15.0-97-generic

Is there a hidden requirement to use a later version of VS Code?

**Comment by dvirtz** [comment]
@evbo do you talk about LargeUTF8 or any parquet file?
I wouldn't expect the arrow backend to work on Linux arm64 as it is precompiled to Linux x64 only. 
Can you try another backend (https://github.com/dvirtz/vscode-parquet-viewer#backends)?

**Comment by evbo** [comment]
Thanks, I tried them all but none work on Linux arm64

**Comment by dvirtz** [comment]
Is it the same error as above?

**Comment by evbo** [comment]
@dvirtz sorry for the delay, parquet-tools just hangs and parquets gives error:
> Error: invalid parquet version

but parquet-wasm works! The reason I didn't think any of them worked is because you actually need to restart VS Code for changes to take effect. Maybe you should update the plugin to notify the user to restart after changing it like some other settings do?
