### ISSUE TITLE
Parquet-wasm backend

### ISSUE THREAD

**Issue by kylebarron** [dvirtz/vscode-parquet-viewer#107]
I came across this repo via the largeutf8 issue in Arrow, and just wanted to mention that in my (biased) opinion one of the most stable off-the-shelf JS Parquet readers is https://github.com/kylebarron/parquet-wasm. That might be less maintenance overhead for you than wrapping the c++ bindings yourself?

**Comment by kylebarron** [comment]
nodejs-polars is a native binding, so it will never work with vscode on the web. It's also a much larger project than just reading parquet files. With parquet-wasm, you can load to an Arrow JS table in two lines of code. It seems like it's quite relevant here

**Comment by dvirtz** [comment]
good points, I'll try `parquet-wasm` then.

**Comment by kylebarron** [comment]
If you hit any issues, feel free to ask me a question!

**Comment by dvirtz** [comment]
Thanks. I'm getting the error
```
RuntimeError: unreachable
        at wasm://wasm/0132be12:wasm-function[2356]:0x3158b9
        at wasm://wasm/0132be12:wasm-function[4456]:0x393d5b
        at wasm://wasm/0132be12:wasm-function[3105]:0x35a45b
        at wasm://wasm/0132be12:wasm-function[90]:0xbde8c
        at wasm://wasm/0132be12:wasm-function[2045]:0x2e9c24
        at wasm://wasm/0132be12:wasm-function[4892]:0x39bbde

      at __wbg_adapter_28 (../../node_modules/parquet-wasm/node/arrow1.js:211:10)
      at real (../../node_modules/parquet-wasm/node/arrow1.js:196:20)
```
from the line
```
    const stream = await readParquetStream(Uri.file(parquetPath).toString());
```

**Comment by kylebarron** [comment]
The stream only works with remote files from an HTTP URL. You can't use it with files on disk. 

Given that you're usually on a local machine, it will be much easier and faster to just load it into a buffer and parse it. https://kylebarron.dev/parquet-wasm/functions/bundler_arrow1.readParquet.html Just pass an `ArrayBuffer` into `readParquet`.
