### ISSUE TITLE
The tool do not works on Windows

### ISSUE THREAD

**Issue by stanislaw-rzewuski** [dvirtz/vscode-parquet-viewer#11]
When I select a parquet file to open I have this
![obraz](https://user-images.githubusercontent.com/51994996/103375002-3dcaed80-4ad9-11eb-8d9a-ed1a652a6e9f.png)

and then whatever I select i do not see anything human readable just bytes like garbage.
I guess it requires parquet tools for windows which do not exists?

**Comment by dvirtz** [comment]
you have two options
- build the jar as described in https://github.com/apache/parquet-mr/tree/master/parquet-tools and point the extension to the jar's path 
- install the tools via pip https://pypi.org/project/parquet-tools/ and either make sure it's in your PATH or point the extension to the executable
![image](https://user-images.githubusercontent.com/7661709/103378407-ea619b00-4aea-11eb-8fec-3e55346aa520.png)

**Comment by stanislaw-rzewuski** [comment]
ok - still not clear for me - no proper manual or installation page
1. i downloaded and installe parquet-tools
2. in command line it is recognized and it is in System PATH
3. so wjhen i run in command window (parquet-tools) I have the response
4. In Visual Studio Code - I go to **File\Preferences\Settings**
![obraz](https://user-images.githubusercontent.com/51994996/103419131-066c4780-4b92-11eb-99b2-22155ab20261.png)


5. i go to **Extensions**
![obraz](https://user-images.githubusercontent.com/51994996/103419160-213ebc00-4b92-11eb-8bb7-873b37a33fb6.png)

6. I go to **parquet-viewer**
![obraz](https://user-images.githubusercontent.com/51994996/103419241-7bd81800-4b92-11eb-8c73-ec85ee17c7f5.png)

7. i type a path to directory where my parquet-tools.exe is located... (doe not matter if it is including or excluding the exe file itself)

8. at the end when I pretend to open the file i do not see anything - just options ofr Hex editor or text edito

![obraz](https://user-images.githubusercontent.com/51994996/103419316-d3768380-4b92-11eb-9df4-2b3bf4f686a0.png)


Please advice actions to make it operational

**Comment by dvirtz** [comment]
do you press `Do you want to open it anyway?` after opening the parquet file?

**Comment by stanislaw-rzewuski** [comment]
I do use this option. below gif "movie" - previous version - not the latest one of the parquet viewer

![parquet_tests_prev_version](https://user-images.githubusercontent.com/51994996/107037025-ce70a980-67ba-11eb-8c5c-227ca6ddafe4.gif)

**Comment by stanislaw-rzewuski** [comment]
and here with old version of the VScode extension:

![parquet_tests_old_version](https://user-images.githubusercontent.com/51994996/107037622-a0d83000-67bb-11eb-823b-50510c95e0c0.gif)

**Comment by stanislaw-rzewuski** [comment]
please note that parquet-tools show (filename) are returning proper data inside ".parquet" file

**Comment by stanislaw-rzewuski** [comment]
Where is the log file located to traceback the extension?

**Comment by dvirtz** [comment]
I really appreciate the effort you put in reporting your findings.
The command used by the extension is `parquet-tools -j <parquet_path>`, but from the output shown is seems that's not supported by the version you have installed.
Can you check which version you have?

**Comment by dvirtz** [comment]
OK. I see that the python port of parquet-tools doesn't have the cat command and also no JSON output.
I'll work on supporting that as well but what I can offer you in the meantime, if you have Java runtime installed, is to download the Java parquet-tools from [here](https://github.com/dvirtz/vscode-parquet-viewer/blob/master/src/test/workspace/parquet-tools-1.12.0-SNAPSHOT.jar), and put its path in the settings as described above.

**Comment by stanislaw-rzewuski** [comment]
PS C:\Windows\System32\WindowsPowerShell\v1.0> pip show parquet-tools
Name: parquet-tools
Version: 0.2.4
Summary: Easy install parquet-tools
Home-page: https://github.com/ktrueda/parquet-tools
Author: Kentaro Ueda
Author-email: kentaro.ueda.kentaro@gmail.com
License: MIT
Location: c:\users\srzew\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages
Requires: pandas, pyarrow, colorama, tabulate, boto3, thrift, halo
Required-by:
PS C:\Windows\System32\WindowsPowerShell\v1.0>

**Comment by stanislaw-rzewuski** [comment]
Please provide link to log file  how the extension makes the parquet  file processing (if not implemented - that is feature needed  it ASAP).
I have 2 other PC-s where the parquet is not opened in any other form than binary file. But i cannot provide screenshots from them.

**Comment by dvirtz** [comment]
There was a problem with displaying the error message which should be fixed in version 1.0.1.
Anyway, as I said, the python port of parquet-tools is not supported right now.
Can you try the Java one as described above?

**Comment by stanislaw-rzewuski** [comment]
Well - It is when using java version of parquet tools.

The need of the logfile (plus it's location placement definition  in "Settings - parquet viewer" will be very beneficial )

we tried also with larger parquets  like 75Mb ant tool do not works - would You like separate BUG on that - (here logfile will be crucial for discovering root cause)?

**Comment by dvirtz** [comment]
The error message displayed in the GIF you've sent in https://github.com/dvirtz/vscode-parquet-viewer/issues/11#issuecomment-774022957 does come from the python parquet tools:
![image](https://user-images.githubusercontent.com/7661709/107509845-ca260100-6bab-11eb-95ac-b425fc493689.png)
Maybe you've switched to Java since then?
You should get a similar error message with version 1.0.1.

I'll work on adding logging.

When you say the tool doesn't work on the 75Mb file, you mean the command line tool? Cause as I understand the extension doesn't work for you on any file. Am I correct?

**Comment by stanislaw-rzewuski** [comment]
Yes i di a switch to java as soon as you suggested.
So i am using parquet-tools in java now.

The parquet-toold in python can oen large parquet file and can generate text or csv file out of (csv size about  500Mb, textfile - 3Gb).
heva not tested the jar parquet tools never the less the main issue is the lack of logging from the plugin. Its verbosity might be a good idea but in principle any logging will be helpful.

Hoe this clarifies teh problem.

**Comment by cstmgl** [comment]
am I the only one that is having a 404 when accessing https://github.com/apache/parquet-mr/tree/master/parquet-tools?
I also tried/succeed to install the tool over pip but honestly I don't know where it lands to put it in my path.
I'll try reading all this comments, but maybe some information in the documentation for more newbie users would be appreciated

**Comment by dvirtz** [comment]
seems like it's been deprecated as it now resides in https://github.com/apache/parquet-mr/tree/master/parquet-tools-deprecated

**Comment by dvirtz** [comment]
@stanislaw-rzewuski logging was added to [v1.0.2](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/dvirtz/vsextensions/parquet-viewer/1.0.2/vspackage), see https://github.com/dvirtz/vscode-parquet-viewer#settings

**Comment by stanislaw-rzewuski** [comment]
Hey - looks like there is missing button for pointing the folder:
![image](https://user-images.githubusercontent.com/51994996/112290685-c350da80-8c8f-11eb-8ef2-3f6eecd3d23e.png)

**Comment by dvirtz** [comment]
I don't think it's currently possible, you can just write the path there.

**Comment by stanislaw-rzewuski** [comment]
Ok. looks like the feature is not doable. I used path copy from "Windows Explorer".
log files are created and the content is more less OK. 
Have to test on parquet-tools executable made in python.

**Comment by dvirtz** [comment]
You might want to checkout version [2.0.0](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/dvirtz/vsextensions/parquet-viewer/2.0.0/vspackage) which doesn't require parquet-tools anymore
