### ISSUE TITLE
Windows 10 - error - cannot find prebuilt arrow module

### ISSUE THREAD

**Issue by mikewop** [dvirtz/vscode-parquet-viewer#121]
I just installed this plugin in VSCode on Windows 10 and am getting the following error tying to open a .parquet file:
**Error: cannot find prebuilt arrow module, either build the module or use another backend: Error: Failed to find binding for arrow-parquet-reader**

**Comment by dvirtz** [comment]
Thanks for opening the issue.
Until this is fixed you can go back to version 2.7.1 or use a different [backend](https://github.com/dvirtz/vscode-parquet-viewer?tab=readme-ov-file#backends).

**Comment by dvirtz** [comment]
Thanks for the report @michaltwarog. Did previous versions of the extension work on this platform?

**Comment by michaltwarog** [comment]
@dvirtz Yes I've downgraded to v2.11.1 and it works perfectly fine.
