### ISSUE TITLE
Does not support LargeList

### ISSUE THREAD

**Issue by evbo** [dvirtz/vscode-parquet-viewer#134]
Before parquet-wasm was the only thing that worked for me on Arm64 Ubuntu, but then I tried opening a parquet file with lists and got:

> Error: Unrecognized type: \"LargeList\" (21)

**Comment by dvirtz** [comment]
Thanks for opening the issue. 
Unfortunately, apache-arrow js library doesn't support `LargeList` yet: https://github.com/apache/arrow/issues/39454 so that's not much I can do about it except for bump the version when it's fixed.
