### ISSUE TITLE
Kaspersky detects a trojan in your extension 

### ISSUE THREAD

**Issue by AlexGarciniGT** [dvirtz/vscode-parquet-viewer#138]
**Os**: Windows 11
**parquet-viewer version**: 2.10.0
**directory**:
~\.vscode\extensions\dvirtz.parquet-viewer-2.10.0\node_modules\parquet-viewer\test\workspace

The issue is in this jar:
**parquet-tools-1.12.0-SNAPSHOT.jar**

Trojan detected type:
**Trojan:Win32/JakyllHyde.gen**

**Comment by dvirtz** [comment]
Thanks for reporting this. 
I just opened #137 a few days ago to deprecate it.
