### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by sdk451** [dvirtz/vscode-parquet-viewer#140]
Require stack:
- c:\Users\simon\.vscode\extensions\dvirtz.parquet-viewer-2.11.0\dist\src\backends\arrow-cpp-backend.js
- c:\Users\simon\.vscode\extensions\dvirtz.parquet-viewer-2.11.0\dist\src\backends\parquet-backend-factory.js
- c:\Users\simon\.vscode\extensions\dvirtz.parquet-viewer-2.11.0\dist\src\parquet-document.js
- c:\Users\simon\.vscode\extensions\dvirtz.parquet-viewer-2.11.0\dist\src\parquet-document-provider.js
- c:\Users\simon\.vscode\extensions\dvirtz.parquet-viewer-2.11.0\dist\src\parquet-editor-provider.js
- c:\Users\simon\.vscode\extensions\dvirtz.parquet-viewer-2.11.0\dist\src\extension.js
- c:\Users\simon\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js

**Comment by dvirtz** [comment]
Thank you for reporting this. Should have a fixed version in a few minutes.
