### ISSUE TITLE
Parquet-Tools install

### ISSUE THREAD

**Issue by george-ly** [dvirtz/vscode-parquet-viewer#16]
Having trouble installing parquet-tools on Windows 10, any help would be greatly appreciated!

**Comment by dvirtz** [comment]
You should have Java installed, then you can download https://repo1.maven.org/maven2/org/apache/parquet/parquet-tools/1.11.1/parquet-tools-1.11.1.jar and put the path to it under `parquet-viewer.parquetToolsPath` setting.

**Comment by cstmgl** [comment]
besides that jar, is there any other jars that need to be in the same path or in the system class path?
which java version does it require? java 11? java 8?

**Comment by dvirtz** [comment]
You might want to checkout version [2.0.0](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/dvirtz/vsextensions/parquet-viewer/2.0.0/vspackage) which doesn't require parquet-tools anymore
