### ISSUE TITLE
error when opening parquet file (parquet-tools exited with code 2: usage parquet-tootls -[h])

### ISSUE THREAD

**Issue by cstmgl** [dvirtz/vscode-parquet-viewer#18]
Hi all,

I had some problems running this tool but might be my lack of knowhow.
I only managed to install the parquet-tools over python/pip.

I've added it to the path and I get this when I open the file in visual studio.
![image](https://user-images.githubusercontent.com/33542778/111620249-c0b13980-87e6-11eb-84a4-e9367d86f48e.png)

But then I click the open as json and I get this error.
![image](https://user-images.githubusercontent.com/33542778/111620259-c444c080-87e6-11eb-8ddc-810135a003d1.png)

Parquet tools seems correctly installed in the system:
![image](https://user-images.githubusercontent.com/33542778/111621288-1a663380-87e8-11eb-9604-26adb67ff4fb.png)

I am assuming I'm failing at something very basic?

**Comment by cstmgl** [comment]
If I use the java version how do I define the path?
Is it just like this:
![image](https://user-images.githubusercontent.com/33542778/111629688-d9731c80-87f1-11eb-8d88-de38fe3a9b2c.png)

**Comment by dvirtz** [comment]
Yes and make sure java.exe is in your path

**Comment by cstmgl** [comment]
I mean I have java (11) in the path
![image](https://user-images.githubusercontent.com/33542778/111648616-d6812780-8803-11eb-903a-e5e15413bb78.png)
![image](https://user-images.githubusercontent.com/33542778/111648654-de40cc00-8803-11eb-8f73-a3884cacd0dc.png)

do I need a specific java? is it java 8? java 11? other? does it need to be the oracle jdk?

**Comment by dvirtz** [comment]
it is tested with java 8, AdoptOpenJDK but Oracle works too.
I'm working on adding more logging so hopefully it will help us find the problem.
In the meantime can you check in a terminal if `java -jar <jar_path> -h` works?

**Comment by cstmgl** [comment]
first thanks for the help and providing feedback.
I think that command does not fail, or fails silently but also does not seem to do anything.

In the cmd prompt
![image](https://user-images.githubusercontent.com/33542778/111782671-98463f80-88b9-11eb-90c7-4b792bb5f667.png)

In the bash
![image](https://user-images.githubusercontent.com/33542778/111782749-adbb6980-88b9-11eb-94c0-3299414a7361.png)
![image](https://user-images.githubusercontent.com/33542778/111782785-bad85880-88b9-11eb-9dd0-4b2cab056549.png)

**Comment by dvirtz** [comment]
You might want to checkout version [2.0.0](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/dvirtz/vsextensions/parquet-viewer/2.0.0/vspackage) which doesn't require parquet-tools anymore
