### ISSUE TITLE
invalid parquet type: DECIMAL

### ISSUE THREAD

**Issue by emorneau** [dvirtz/vscode-parquet-viewer#34]
Error received when trying to open a parquet file. Why?

**Comment by dekiesel** [comment]
I have the same issue. Unfortunately I can't share the parquet file.

Seems to be a parquets issue: https://github.com/dvirtz/parquets/issues/17

**Comment by dvirtz** [comment]
Sorry, I don't think I'll get to that parquets issue soon. I didn't write that library, just forked it to make some small fixes,
The long term solution will likely be using one of the official packages currently maintained under https://github.com/apache/arrow
