### ISSUE TITLE
Does not read all columns.

### ISSUE THREAD

**Issue by mcronaldp** [dvirtz/vscode-parquet-viewer#35]
I have one parquet file who's content looks like this:
![image](https://user-images.githubusercontent.com/13559262/144427860-ad307fc5-2d88-4ce7-89f3-48626ec1f90a.png)
After i open it in Visual studio code i'll get this:
![image](https://user-images.githubusercontent.com/13559262/144428014-d6bfad09-203d-4109-abd5-7088cdfd3509.png)

You notice that the second column Date is not visible, but reads NULL
In the DimDate.zip you will find the .parquet file i worked with.
[DimDate.zip](https://github.com/dvirtz/vscode-parquet-viewer/files/7642113/DimDate.zip)

It looks like it can't handle Date fields well.
Because if i cast it like this it goes wrong:
CAST(Date AS DATE) AS Date,  
When i cast it like this it goes well:
CAST(Date AS datetime) AS Date,
To be absolutely clear. it only goes wrong in visual studio code when reading the parquet file.
If i read the parquet file in other programs and in Azure sql script is works fine.

Then it does work nice.
![image](https://user-images.githubusercontent.com/13559262/144429872-b63f2323-a300-4313-8260-294adbd98942.png)

regards, Ronald

**Comment by dvirtz** [comment]
Thanks for opening the issue. It should be resolved in v2.1.2
