### ISSUE TITLE
Old versions of files appear

### ISSUE THREAD

**Issue by mhkeller** [dvirtz/vscode-parquet-viewer#38]
When I rewrite a previously viewed file, I see the old version, not what I just overwrote it with.

**Comment by dvirtz** [comment]
Thanks for opening the issue.

The view is cached for performance reasons. I'll see what I can do to invalidate the cache when the underlying file changes.
In the meantime, reloading the window (`Developer: Reload Window` command) should help.

**Comment by dvirtz** [comment]
still working on that

**Comment by karimelghazouly** [comment]
same issue here, this costed me around 2 hours of debugging trying to figure out why the new file has not changed.

**Comment by dvirtz** [comment]
Sorry about your time loss. 
Unfortunately, I hadn't time to work on that. PRs are welcome.
