### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kishaningithub** [dvirtz/vscode-parquet-viewer#42]
Got error RangeError: Maximum call stack size exceeded when trying to open a 418 MB parquet file with compression as snappy

**Comment by dvirtz** [comment]
Thanks for opening up an issue.
It will be really helpful if you could upload that file somewhere for me to reproduce.

**Comment by dvirtz** [comment]
@kishaningithub Can you check if installing https://github.com/dvirtz/vscode-parquet-viewer/suites/6821055446/artifacts/262551646 solves your problem?
To install, unzip and run 
```
code  --install-extension parquet-viewer-2.1.3.vsix
```
