### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by hangxie** [dvirtz/vscode-parquet-viewer#44]
I have some parquet files (https://github.com/hangxie/parquet-tools/tree/main/cmd/testdata) created by my tool written in go, some of them are not readable by this extension, would you please use them as test cases? Their corresponding JSON/JSONL dump can be found under `golden/`, they are not exactly the same as Java or Python parquet-tools output though I tried my best.

So far the problem is DECIMAL, you can try it with `reinterpret-scalar.parquet` which is a flat table, once this works I'd like to see this extension supports `all-types.parquet` which has quite some data types and complicated structures.

I don't know enough (anything?) about TypeScript, but I can help if you have any questions about the test data or want to generate some more test cases.

**Comment by dvirtz** [comment]
This is a bug of the [parquets](https://github.com/dvirtz/parquets) backend rather then this extension per se. I've opened https://github.com/dvirtz/parquets/issues/17 to track that.
