### ISSUE TITLE
Error: invalid parquet version

### ISSUE THREAD

**Issue by martin-reisenhofer-paessler** [dvirtz/vscode-parquet-viewer#55]
If I try to open a parquet  file, I always get the error: invalid parquet version
Currently, I use version 2.2.0
Problem happens if I export a parquet file with pyarrow 9.0.0, pyarrow 8.0.0 works. 
Thx for support, for this fantastic addon.

**Comment by dvirtz** [comment]
Thanks for opening an issue. It will be much easier to debug if you can attach an example parquet which causes the error to appear.

**Comment by dvirtz** [comment]
Looks like the backend only supports parquet version 1. I guess `pyarrow` changed the default version it writes between v8 and v9.
You can specify `version=1.0` when writing though pyarrow, to enable this extension to read the file, see https://arrow.apache.org/docs/python/parquet.html#parquet-file-writing-options

**Comment by martin-reisenhofer-paessler** [comment]
Ah ok, thx for the input.

**Comment by saritvakrat** [comment]
@martin-reisenhofer-paessler were you able to find a parser that works with V2?

**Comment by dvirtz** [comment]
@saritvakrat both `arrow` (which is the default now) and `parquet-wasm` backends should be able to show V2 files.
