### ISSUE TITLE
[Feature request] Make this extension available in open-vsx registry

### ISSUE THREAD

**Issue by kishaningithub** [dvirtz/vscode-parquet-viewer#56]
I am a [vscodium](https://vscodium.com/) user, as of now i cannot find this extension in the [open vsx registry here](https://open-vsx.org/)

Registry URL: https://open-vsx.org/

It would be great if this extension is also made available there

**Comment by dvirtz** [comment]
available at https://open-vsx.org/extension/dvirtz/parquet-viewer
