### ISSUE TITLE
Does it run on Windows?

### ISSUE THREAD

**Issue by pdesmarets** [dvirtz/vscode-parquet-viewer#6]
Viewer 0.1.3 is installed and enabled.  Parquet-tools is in the path.  But I still see gibberish.  What am I doing wrong?

**Comment by dvirtz** [comment]
Did you try to use the command?

[image: image.png]

**Comment by dvirtz** [comment]
![image](https://user-images.githubusercontent.com/7661709/63654067-08442080-c77e-11e9-9e9f-299e32d7da14.png)

**Comment by pdesmarets** [comment]
Thanks for your quick response.  Yes, I did with same result unfortunately.  

![image](https://user-images.githubusercontent.com/10139210/63668829-8a613300-c7d8-11e9-9c64-d75458484079.png)

Both VS Code and parquet-tools (as downloaded from git) are in Windows PATH.  What else am I missing?  Do parquet-tools need to be built?

**Comment by dvirtz** [comment]
Can you run parquet-tools from the terminal on that parquet file?

**Comment by pdesmarets** [comment]
No, I'm getting the error
parquet-tools : The term 'parquet-tools' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ parquet-tools schema
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (parquet-tools:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

What is your extension looking for?  A .jar or something else?

**Comment by dvirtz** [comment]
It's looking for an executable. I'm using the version installed by homebrew which has a bash script under `/usr/local/bin/parquet-tools` which contains 
```bash
#!/bin/bash
exec java  -jar /usr/local/Cellar/parquet-tools/1.10.0/libexec/parquet-tools-1.10.0.jar "$@"
```

I guess adding such a script to your path will do the work.

**Comment by dvirtz** [comment]
Closing. Please comment if that still doesn't work.

**Comment by pdesmarets** [comment]
I was finally able to create a Windows build of parquet-tools.  But I still can't make it work in VSC.  I'll just continue with the parquet-tools command line.  Thanks

**Comment by dvirtz** [comment]
In that case I'll keep it open. I'll try to look at it when I'm free.

**Comment by dvirtz** [comment]
Version 0.1.4 enables putting the path to a `parquet-tools` jar in the settings. 
The extension will use this jar in that case.
I've tested it on Windows and it seems to work.

**Comment by pdesmarets** [comment]
Thanks!  I'll take a look.
