### ISSUE TITLE
Broken support for parquet-tools

### ISSUE THREAD

**Issue by tomers** [dvirtz/vscode-parquet-viewer#66]
I am using `parquet-tools==0.2.11`, and it seems that when setting this extension to use `parquet-tools`, it tries to invoke the `cat` command, which apparently no longer supported. Instead the user gets this error:
```
Error: while reading foo.parquet: parquet-tools exited with code 2 usage: parquet-tools [-h] {show,csv,inspect} ... parquet-tools: error: argument {show,csv,inspect}: invalid choice: 'cat' (choose from 'show', 'csv', 'inspect')
```

**Comment by dvirtz** [comment]
The support is for the deprecated java client not the python one.
