### ISSUE TITLE
Cannot view nyc tax yellow cab data

### ISSUE THREAD

**Issue by alberttwong** [dvirtz/vscode-parquet-viewer#74]
It just runs and runs.... https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page

It's about 50 megs. https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet

**Comment by dvirtz** [comment]
Thank you for opening the issue, I can reproduce it locally. 
It also blows up my RAM.

**Comment by dvirtz** [comment]
I hope it can be addressed by https://github.com/dvirtz/vscode-parquet-viewer/pull/73
