### ISSUE TITLE
The plugin stays loading forever.

### ISSUE THREAD

**Issue by diegozabala** [dvirtz/vscode-parquet-viewer#79]
Input file: .snappy.parquet file
size: 1MB
Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2,6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	1916.80.2.0.0 (iBridge: 20.16.3045.0.0,0)
  OS Loader Version:	564.40.4~66

**Comment by dvirtz** [comment]
Thanks for opening the issue.
Can you try with the `arrow` backend: https://github.com/dvirtz/vscode-parquet-viewer#arrow
If that's not working, it would be best if you could attach the problematic file here.

**Comment by dvirtz** [comment]
probably the same as #81

**Comment by dvirtz** [comment]
Please try v2.3.1 and reopen if still fails.

**Comment by diegozabala** [comment]
Thanks a lot [dvirtz], it's working on my side now. ty
