### ISSUE TITLE
Opening a file never ends

### ISSUE THREAD

**Issue by egor-ryashin** [dvirtz/vscode-parquet-viewer#85]
I have a small test file that I checked with `parquet-tools`:
```
parquet-tools dump ~/arrow.parquet 
row group 0 
--------------------------------------------------------------------------------
a:  INT32 UNCOMPRESSED DO:4 FPO:30 SZ:77/77/1.00 VC:3 ENC:PLAIN,RLE,RL [more]...

    a TV=3 RL=0 DL=0 DS: 3 DE:PLAIN
    ----------------------------------------------------------------------------
    page 0:               DLE:RLE RLE:RLE VLE:RLE_DICTIONARY ST:[min:  [more]... VC:3

INT32 a 
--------------------------------------------------------------------------------
*** row group 1 of 1, values 1 to 3 *** 
value 1: R:0 D:0 V:1
value 2: R:0 D:0 V:2
value 3: R:0 D:0 V:3
```
I click to open in VsCode and it never ends.

**Comment by dvirtz** [comment]
What extension version you're on? 
This sounds similar to https://github.com/dvirtz/vscode-parquet-viewer/issues/81 which was fixed with v2.3.1

**Comment by egor-ryashin** [comment]
v2.3.3

**Comment by dvirtz** [comment]
Please look at the `Extension Host` output window for any errors involving `parquet-tools` and paste them here.

**Comment by egor-ryashin** [comment]
here

**Comment by egor-ryashin** [comment]
[example.zip](https://github.com/dvirtz/vscode-parquet-viewer/files/12284457/example.zip)

**Comment by egor-ryashin** [comment]
Seeing `Error: invalid parquet version` in the popup.

**Comment by dvirtz** [comment]
This version isn't supported by the `parquets` backend, although it still shouldn't hang opening the file.
Can you try switch to `arrow` backend: https://github.com/dvirtz/vscode-parquet-viewer#arrow

**Comment by egor-ryashin** [comment]
I actually opened that file with `parquet-tools` backend.
But a tried a larger file and cannot open it with all 3 backends now.

**Comment by dvirtz** [comment]
I'm glad you had success with another backend. 
There's a known problem with large files: #74.
I want to implement a paged view to solve that, but it's a rather large effort.
