### ISSUE TITLE
invalid parquet type: DECIMAL 

### ISSUE THREAD

**Issue by AartBluestoke** [dvirtz/vscode-parquet-viewer#88]
possibly same issue as the closed #34 (closed a year ago)
- microsoft's synapse link seems to be creating parquet files with this data type - there could be a large userbase unable to use your plugin here :(

**Comment by dvirtz** [comment]
Thanks for opening the issue. 
This should be solved now by using the `arrow` backend: https://github.com/dvirtz/vscode-parquet-viewer#arrow

**Comment by AartBluestoke** [comment]
Thanks, changing the backend solved this.
